name: changeset
on:
  push:
    branches:
      - 'develop'
jobs:
  changeset:
    name: changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn
      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
